name: Honar deploy CI/CD

on:
  push:
    branches: 
    - main

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Connect by SSH and sync repository
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_ADDRESS }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd $PROJECT_DIR
          git pull origin main
          npm install
          npm run build
          pm2 start npm --name new-honar-strapi -- run start
